### ISSUE TITLE
Can we change the docker image base to busybox?

### ISSUE THREAD

**Issue by bobbytables** [nats-io/nats-streaming-docker#6]
When running nats in production kuberenetes cluster it's difficult to see what's happening inside of it. For example, I'm fairly certain that we're hitting a memory constraint when running the container but it's hard to tell because the `scratch` base doesn't have a shell or `ps` to be able to dig deeper. Running containers in kubernetes in the same cgroup is also difficult.

**Comment by kozlovic** [comment]
The idea of using `scratch` is that it is a very small image. But it seems that with `busybox` we would not increase the size by too much. We need to discuss this internally.
We were planning on issuing a release today for `v0.5.0` and still may go with `scratch` for this release, but keep in mind that it would be easy for you to run your own docker image based on `busybox`. But again, we will discuss and get back to you on that. Thanks!

**Comment by bobbytables** [comment]
Awesome. Well none the less really looking forward to 0.5.0. Hope to see that today.

**Comment by rockymadden** [comment]
I've run into another problem with Kubernetes that would require something like `busybox`:
* Say you want to enforce a simple auth token
* You use a k8s secret to store this auth token value
* You then need to get nats-streaming to use it and you could technically pass it in via the `--auth` but then anyone doing a `describe` can see it
* You decide to use `--config`, in which you will pass secret things in here some config file
* You mount your secret only to find that `volumeMounts` in k8s cannot point to `/` and since no other directories exist in the image your hands are tied

**Comment by wallyqs** [comment]
Hi @rockymadden, in the NATS Operator a configmap/secret is being mounted using the official image, so I think it could work similar in NATS Streaming (related to the last point you mention).

```yaml
spec:
  # ...
  volumes:
    - name: "config"
      configMap:
        name: "nats-config"
  containers:
    - name: nats
      command: ["/gnatsd", "--cluster", "nats://0.0.0.0:6222", "--config", "/etc/nats-config/nats.conf"]
      image: "nats:1.0.4"

      volumeMounts:
      - name: "config"
        mountPath: "/etc/nats-config/"
```
